### ISSUE TITLE
The bobbing cat gif is distracting

### ISSUE THREAD

**Issue by SymphonySimper** [LazyRen/LazyRen.github.io#58]
It would be nice to hide the **cat** Gif in the sidebar, or if you could make the sidebar collapse it would be great.

**Comment by LazyRen** [comment]
It's too bad you didn't like it T.T I invested some time to make one...

I never thought it would be distracting. I'll find a new static image to replace one in near future.

Thank you for the feedback :)

**Comment by SymphonySimper** [comment]
The cat is super cute :sweat_smile: , but it would be even cuter if its static.
And thanks a lot for your study notes, they helped me a lot in doing the rustlings exercises.

**Comment by LazyRen** [comment]
I made gif to iterate only once. After that, it will remain as static image.

I'm glad to hear that it helps you. Thank you for visiting my blog and feel free to leave any comment or issue later for anything.

Best regards,
Lee, DaeIn.
