### ISSUE TITLE
Need some assistance, Related posts according to categories

### ISSUE THREAD

**Issue by iAmG-r00t** [LazyRen/LazyRen.github.io#63]
Hey, @LazyRen first thank you for your blog it motivated me to move my blog from blogger to this specific theme. Now I am having one issue which I think you can assist me in fixing it. I bought the pro version of hydejack my issue is that for me to have a post shown at the bottom as [related](https://hydejack.com/docs/basics/#adding-related-posts-to-a-post) I have to enter the specific path or URL of the posts manually. I find that tiresome and would love to see if there could be a way to get two posts that are in the same category apart from the current post below.

I know you haven't implemented this option on your site, but I have already seen the code responsible for this just need some help with the logic. (Would also like to note that I have seen someone who has managed to do this with tags on the same [theme](https://github.com/colindembovsky/colindembovsky.github.io/commit/c30e9c8e9a9ecbc27533998dfa26a7e71ebfb9ca) but I prefer the category option)

I found a way to loop through the posts with certain categories but my issue is that I am unable to assign the post to two variables... how can I achieve that?

Code location: `_includes/components/related-posts.html` & `_includes/pro/related-posts.html`

```html
<!-- the below code is from the pro directory-->
{% assign post = page %}

{% if page.related_posts %}
  {% if major >= 4 and minor >= 1 %}
    {% assign related_posts = site.posts | where_exp:"post", "page.related_posts contains post.path or page.related_posts contains post.url" %}
  {% else %}
    {% assign related_posts_1 = site.posts | where_exp:"post", "page.related_posts contains post.path" %}
    {% assign related_posts_2 = site.posts | where_exp:"post", "page.related_posts contains post.url" %}
    {% assign related_posts = related_posts_1 | concat:related_posts_2 %}
  {% endif %}
{% elsif site.hydejack.use_lsi or site.use_lsi %}
  {% assign related_posts = site.related_posts %}
{% elsif post.categories.first %}
  <!--original code starts here-->
  {% assign related_posts = site.categories[post.categories.first] | where_exp:"post", "post.url != page.url" %}
  <!--ends here-->
  <!--help here-->
  {% capture category %}{{ page.categories | first }}{% endcapture %}
  {% for post in site.categories[category] limit: 3 %}
    <!--how can I assign post 1 and two two variables related_posts_1 and related_posts_2 respectively?-->
    {% assign related_posts = site.categories[post.categories.first] | where_exp:"post", "post.url != page.url" %}
    {% assign related_posts_2 = site.posts | where_exp:"post", "page.related_posts contains post.url" %}
    {% assign related_posts = related_posts_1 | concat:related_posts_2 %}
  {% endfor %}
  <!-end of help-->
{% elsif post.tags.first %}
  {% assign related_posts = site.tags[post.tags.first] | where_exp:"post", "post.url != page.url" %}
{% else %}
  {% assign related_posts = site.related_posts %}
{% endif %}

{% if related_posts.size > 0 %}
<aside class="other-projects related mb0" role="complementary">
  <h2>{{ site.data.strings.related_posts | default:"Related Posts" }}</h2>
  <div class="columns">
    {% for post in related_posts limit:2 %}
      <div class="column column-1-2">
        {% if post %}
          {% include_cached pro/post-card.html post=post %}
        {% else %}
          Post with path <code>{{ post_path }}</code> not found.
        {% endif %}
      </div>
    {% endfor %}
  </div>
</aside>
{% endif %}
```

Thank you once again, looking forward to your reply.

**Comment by LazyRen** [comment]
Hello, @iAmG-r00t. First of all, it's great to hear that my posts have inspired someone to use the theme :) Means a lot to me. Thank you.

Back to the post, I don't understand why you are trying to do that with your own code. Original code
```liquid
{% assign related_posts = site.categories[post.categories.first] | where_exp:"post", "post.url != page.url" %}
```
already capture posts from the current (if multiple, first of) category and later prints two of them as "Related Posts".

In case you are missing (pretty sure you are not), just add `related` to the [`_config.yml`](https://github.com/LazyRen/LazyRen.github.io/blob/master/_config.yml#L238) and set [`use_lsi`](https://github.com/iAmG-r00t/blog/blob/main/_config.yml#L222) to `false` (it's currently `true` in your blog)

Is there a something I am missing here?
I think I'm misunderstanding the purpose of your new implementation.
Can you please elaborate more?

**Comment by iAmG-r00t** [comment]
Hey, @LazyRen I am not missing but the two posts that are being shown at the bottom are not related to the current post according to category.

Let me update my blog for you to see, what I mean.

**Comment by iAmG-r00t** [comment]
Ohhh it works, I had tried it before but without disabling `lsi`. If I may ask what is the purpose of LSI, and why when disabled it works. Because previously it would show me the latest two posts as related when `use_lsi` was `true`

**Comment by LazyRen** [comment]
> Because previously it would show me the latest two posts as related when use_lsi was true

`lsi` is a [Jekyll's configuration](https://jekyllrb.com/docs/configuration/options/) for the generation of the related posts. The two latest posts are probably the result of the `LSI`.

[This line](https://github.com/iAmG-r00t/blog/blob/main/_includes/pro/related-posts.html#L11) prevented you from the default behavior when `use_lsi` option was set.

It's good to see you have found the way to resolve it. I kinda thought that `use_lsi` could be the cause of the issue haha.

**Comment by iAmG-r00t** [comment]
Okay, thank you 😄
