### ISSUE TITLE
How do you enable the "search" functionallity within your github-page?

### ISSUE THREAD

**Issue by ANYMS-A** [LazyRen/LazyRen.github.io#79]
Hey Ren,

I really like your github page's style and I'd like to know how can I enable the "search" functionality with the `hydejack` theme? 

When I clone and build the default `hydejack` repo, I find seems there isn't a "search field" at the top of the homepage

**Comment by LazyRen** [comment]
Hello @ANYMS-A.
It's a one of the feature that comes with [Hydejack PRO](https://hydejack.com/download/).

You must purchase the license to get full feature of the Hydejack theme.
