### ISSUE TITLE
Resume did not work correctly

### ISSUE THREAD

**Issue by re-toor** [LazyRen/LazyRen.github.io#87]
Hi Lazy Ren,

I hope you are doing well.
I just created my blog with Hydejack like you, but I can not export my resume pdf correctly.
When I used npm export with **jsonresume-them-hydejack**, the pdf was exported successfully, but the content of pdf didn't display that look like in the resume tab. (Image below)

I have opened issue in hydejack starter kit, but I was not received any solution. 
Can you please check with that?
Thank you so much!

![image](https://github.com/LazyRen/LazyRen.github.io/assets/71746391/f8c9145b-7e25-4fe9-bf99-abc0a7b79879)

**Comment by LazyRen** [comment]
Hello @re-toor, I'm sorry I don't have any experience with `jsonresume-them-hydejack`, so I'm afraid I cannot help you on this issue.
